# Generated by Django 4.0.4 on 2022-04-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qspricehistory',
            old_name='price',
            new_name='current_price',
        ),
        migrations.AddField(
            model_name='connecttable',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
