# Generated by Django 4.0.4 on 2022-04-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_price_qspricehistory_current_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='departure',
            new_name='departament',
        ),
    ]
